export const BECOME_GAME_STATE = 'BECOME_GAME_STATE';
export const MAKE_HUMAN_MOVE = 'MAKE_HUMAN_MOVE';
export const COMPUTER_MOVE_START = 'COMPUTER_MOVE_START';
export const COMPUTER_MOVE_SUCCESS = 'COMPUTER_MOVE_SUCCESS';
export const COMPUTER_MOVE_FAILURE = 'COMPUTER_MOVE_FAILURE';
export const ADD_RESULT = 'ADD_RESULT';
