export const START_NEW_GAME = 'START_NEW_GAME';
export const GAME_OVER = 'GAME_OVER';
export const MAKE_HUMAN_MOVE = 'MAKE_HUMAN_MOVE';
export const MAKE_COMPUTER_MOVE_REQUEST = 'MAKE_COMPUTER_MOVE_REQUEST';
export const MAKE_COMPUTER_MOVE_SUCCESS = 'MAKE_COMPUTER_MOVE_SUCCESS';
export const MAKE_COMPUTER_MOVE_FAILURE = 'MAKE_COMPUTER_MOVE_FAILURE';
export const NAVIGATE_TO_CELL = 'NAVIGATE_TO_CELL';
