export const START_NEW_GAME = 'START_NEW_GAME';
export const GAME_OVER = 'GAME_OVER';
export const MAKE_HUMAN_MOVE = 'MAKE_HUMAN_MOVE';
export const COMPUTER_MOVE_REQUEST = 'COMPUTER_MOVE_REQUEST';
export const COMPUTER_MOVE_SUCCESS = 'COMPUTER_MOVE_SUCCESS';
export const COMPUTER_MOVE_FAILURE = 'COMPUTER_MOVE_FAILURE';
